apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  mongodb_uri: {{ .Values.secrets.mongodbUri | quote }}
  mongodb_db: {{ .Values.secrets.mongodbDb | quote }}
  jwt_secret: {{ .Values.secrets.jwtSecret | quote }}
